### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'bash'

### ISSUE THREAD

**Issue by Korijn** [conda/conda-build#1035]
Our builds are failing on Codeship, thanks to a bug introduced 3 days ago in [1.21.0](https://github.com/conda/conda-build/releases/tag/1.21.0), commit f836dd648a6ba46220539d0007e56aa5462f564d:

```
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
File "/home/rof/miniconda/bin/conda-build", line 5, in <module>
sys.exit(main())
File "/home/rof/miniconda/lib/python3.5/site-packages/conda_build/main_build.py", line 140, in main
args_func(args, p)
File "/home/rof/miniconda/lib/python3.5/site-packages/conda_build/main_build.py", line 380, in args_func
args.func(args, p)
File "/home/rof/miniconda/lib/python3.5/site-packages/conda_build/main_build.py", line 327, in execute
dirty=args.dirty)
File "/home/rof/miniconda/lib/python3.5/site-packages/conda_build/build.py", line 558, in build
deactivate_env()
File "/home/rof/miniconda/lib/python3.5/site-packages/conda_build/environ.py", line 440, in deactivate_env
return activate_or_deactivate_env("deactivate")
File "/home/rof/miniconda/lib/python3.5/site-packages/conda_build/environ.py", line 429, in activate_or_deactivate_env
vars = subprocess.check_output(["bash", "-c", cmd], env=os.environ)
File "/home/rof/miniconda/lib/python3.5/subprocess.py", line 629, in check_output
**kwargs).stdout
File "/home/rof/miniconda/lib/python3.5/subprocess.py", line 696, in run
with Popen(*popenargs, **kwargs) as process:
File "/home/rof/miniconda/lib/python3.5/subprocess.py", line 950, in __init__
restore_signals, start_new_session)
File "/home/rof/miniconda/lib/python3.5/subprocess.py", line 1544, in _execute_child
raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'bash'
```

`conda info -a`:

```
Current conda install:

platform : linux-64
conda version : 4.1.1
conda-build version : 1.21.0
python version : 3.5.1.final.0
requests version : 2.9.1
root environment : /home/rof/miniconda  (writable)
default environment : /home/rof/miniconda
envs directories : /home/rof/miniconda/envs
package cache : /home/rof/miniconda/pkgs
channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
https://repo.continuum.io/pkgs/free/noarch/
https://repo.continuum.io/pkgs/pro/linux-64/
https://repo.continuum.io/pkgs/pro/noarch/
config file : /home/rof/.condarc
is foreign system : False

# conda environments:
#
root                  *  /home/rof/miniconda

sys.version: 3.5.1 |Continuum Analytics, Inc.| (defau...
sys.prefix: /home/rof/miniconda
sys.executable: /home/rof/miniconda/bin/python3
conda location: /home/rof/miniconda/lib/python3.5/site-packages/conda
conda-build: /home/rof/miniconda/bin/conda-build
conda-convert: /home/rof/miniconda/bin/conda-convert
conda-develop: /home/rof/miniconda/bin/conda-develop
conda-env: /home/rof/miniconda/bin/conda-env
conda-index: /home/rof/miniconda/bin/conda-index
conda-inspect: /home/rof/miniconda/bin/conda-inspect
conda-metapackage: /home/rof/miniconda/bin/conda-metapackage
conda-pipbuild: /home/rof/miniconda/bin/conda-pipbuild
conda-render: /home/rof/miniconda/bin/conda-render
conda-server: /home/rof/miniconda/bin/conda-server
conda-sign: /home/rof/miniconda/bin/conda-sign
conda-skeleton: /home/rof/miniconda/bin/conda-skeleton
user site dirs: 

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: <not set>
CONDA_ENVS_PATH: <not set>
LD_LIBRARY_PATH: <not set>
PATH: /home/rof/miniconda/bin:/home/rof/.nvm/v0.10.45/bin:/home/rof/.rvm/gems/ruby-2.1.7/bin:/home/rof/.rvm/gems/ruby-2.1.7@global/bin:/home/rof/.rvm/rubies/ruby-2.1.7/bin:node_modules/.bin:/home/rof/.packer:/home/rof/dart-sdk/bin:/home/rof/appengine/python_appengine:/home/rof/appengine/go_appengine:/home/rof/appengine/java_appengine/bin:/home/rof/cache/composer/bin:/home/rof/cache/bundler/bin:/home/rof/firefox:/home/rof/.slimerjs:/home/rof/.phpenv/bin:/home/rof/.phpenv/shims:/home/rof/.virtualenv/bin:/home/rof/bin:/home/rof/.gradle/gradle/bin:/home/rof/.ant/ant/bin:/home/rof/.maven/maven/bin:/home/rof/.phantomjs/bin:/home/rof/.casperjs/bin:/home/rof/node_modules/.bin:/home/rof/.config/composer/vendor/bin:node_modules/.bin:/home/rof/.packer:/home/rof/dart-sdk/bin:/home/rof/appengine/python_appengine:/home/rof/appengine/go_appengine:/home/rof/appengine/java_appengine/bin:/home/rof/cache/composer/bin:/home/rof/cache/bundler/bin:/home/rof/firefox:/home/rof/.slimerjs:/home/rof/.phpenv/bin:/home/rof/.phpenv/shims:/home/rof/.virtualenv/bin:/home/rof/bin:/home/rof/.gradle/gradle/bin:/home/rof/.ant/ant/bin:/home/rof/.maven/maven/bin:/home/rof/.phantomjs/bin:/home/rof/.casperjs/bin:/home/rof/node_modules/.bin:/home/rof/.config/composer/vendor/bin:/home/rof/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin:/home/rof/.rvm/bin
PYTHONHOME: <not set>
PYTHONPATH: <not set>

WARNING: could not import _license.show_info
# try:
# $ conda install -n root _license
```

**Comment by msarahan** [comment]
So, the bug is at https://github.com/conda/conda-build/commit/f836dd648a6ba46220539d0007e56aa5462f564d#diff-ac55d744935b1f37a3369258b88e8f1fR372 ? (in other words, you don't have bash on your system?)  I don't think this showed up in our tests, because bash is always available on the Travis build environment.

This was a bad assumption on my part, that bash would always be available.  I'll try to restore the parent shell detection, and fall back to 'sh', but then I'm afraid the -l -c arguments may not be generalizable.

**Comment by Korijn** [comment]
I've just checked by opening a debug session on Codeship:

```
rof@railsonfire_595d5430-189c-0134-2c5d-222e7a7b8269_da10e461d9b9:~$ which bash
/bin/bash
rof@railsonfire_595d5430-189c-0134-2c5d-222e7a7b8269_da10e461d9b9:~$ bash
rof@railsonfire_595d5430-189c-0134-2c5d-222e7a7b8269_da10e461d9b9:~$
```

So `bash`'s availability is apparently not the problem?

**Comment by msarahan** [comment]
Yeah, thanks.  I think I am hitting this problem elsewhere, and hope to have a fix soon.  Work in progress at https://github.com/conda/conda-build/pull/1036 - any time you have for testing would be much appreciated, but maybe wait until the CIs are green?

**Comment by Korijn** [comment]
Well, in our setup, we actually deactivate the active environment (if any) before calling conda build. Not sure if that helps...

We've disabled conda-build on our linux CI for now, luckily AppVeyor is still passing.

**Comment by msarahan** [comment]
I think this is fixed by #1044 - please update to conda-build 1.21.1 (should be available shortly) and try again.

**Comment by msarahan** [comment]
@Korijn - if you have a spare moment to test, I'd appreciate your take on whether this bug can be closed or not (with conda-build 1.21.2 and conda 4.1.4).

**Comment by Korijn** [comment]
@msarahan Everything seems to be working again, thanks!

**Comment by msarahan** [comment]
Excellent, thanks for your time.  Closing this issue.

**Comment by Diti24** [comment]
Hi all,
I'm having probably the same error but it still persists with  conda-build version : 1.21.2. I get the error when trying to run the jupitter-notebook:
```
anaconda3/bin/jupyter-notebook 
[W 11:39:41.464 NotebookApp] Unrecognized JSON config file version, assuming version 1
Traceback (most recent call last):
  File "anaconda3/bin/jupyter-notebook", line 6, in <module>
    sys.exit(notebook.notebookapp.main())
  File "/mnt/disk2/opt/anaconda3/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/mnt/disk2/opt/anaconda3/lib/python3.5/site-packages/traitlets/config/application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/mnt/disk2/opt/anaconda3/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/mnt/disk2/opt/anaconda3/lib/python3.5/site-packages/notebook/notebookapp.py", line 1069, in initialize
    self.init_configurables()
  File "/mnt/disk2/opt/anaconda3/lib/python3.5/site-packages/notebook/notebookapp.py", line 837, in init_configurables
    parent=self,
  File "/mnt/disk2/opt/anaconda3/lib/python3.5/site-packages/nb_conda_kernels/manager.py", line 19, in __init__
    specs = self.find_kernel_specs() or {}
  File "/mnt/disk2/opt/anaconda3/lib/python3.5/site-packages/nb_conda_kernels/manager.py", line 129, in find_kernel_specs
    self.conda_info = self._conda_info()
  File "/mnt/disk2/opt/anaconda3/lib/python3.5/site-packages/nb_conda_kernels/manager.py", line 29, in _conda_info
    p = subprocess.check_output(["conda", "info", "--json"]
  File "/mnt/disk2/opt/anaconda3/lib/python3.5/subprocess.py", line 629, in check_output
    **kwargs).stdout
  File "/mnt/disk2/opt/anaconda3/lib/python3.5/subprocess.py", line 696, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/mnt/disk2/opt/anaconda3/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/mnt/disk2/opt/anaconda3/lib/python3.5/subprocess.py", line 1544, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'conda'
```

And the conda info gives me:
```
./conda info -a
Current conda install:

             platform : linux-64
        conda version : 4.1.5
    conda-env version : 2.5.1
  conda-build version : 1.21.2
       python version : 3.5.1.final.0
     requests version : 2.10.0
     root environment : /mnt/disk2/opt/anaconda3  (writable)
  default environment : /mnt/disk2/opt/anaconda3
     envs directories : /mnt/disk2/opt/anaconda3/envs
        package cache : /mnt/disk2/opt/anaconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False

# conda environments:
#
root                  *  /mnt/disk2/opt/anaconda3

sys.version: 3.5.1 |Anaconda 4.1.0 (64-bit)| (default...
sys.prefix: /mnt/disk2/opt/anaconda3
sys.executable: /mnt/disk2/opt/anaconda3/bin/python3
conda location: /mnt/disk2/opt/anaconda3/lib/python3.5/site-packages/conda
conda-build: /mnt/disk2/opt/anaconda3/bin/conda-build
conda-convert: /mnt/disk2/opt/anaconda3/bin/conda-convert
conda-develop: /mnt/disk2/opt/anaconda3/bin/conda-develop
conda-env: /mnt/disk2/opt/anaconda3/bin/conda-env
conda-index: /mnt/disk2/opt/anaconda3/bin/conda-index
conda-inspect: /mnt/disk2/opt/anaconda3/bin/conda-inspect
conda-metapackage: /mnt/disk2/opt/anaconda3/bin/conda-metapackage
conda-pipbuild: /mnt/disk2/opt/anaconda3/bin/conda-pipbuild
conda-render: /mnt/disk2/opt/anaconda3/bin/conda-render
conda-server: /mnt/disk2/opt/anaconda3/bin/conda-server
conda-sign: /mnt/disk2/opt/anaconda3/bin/conda-sign
conda-skeleton: /mnt/disk2/opt/anaconda3/bin/conda-skeleton
user site dirs: 

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: <not set>
CONDA_ENVS_PATH: <not set>
LD_LIBRARY_PATH: <not set>
PATH: /usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
PYTHONHOME: <not set>
PYTHONPATH: <not set>

WARNING: could not import _license.show_info
# try:
# $ conda install -n root _license
```

I recently fresh installed the latest Anaconda package:
Anaconda3-4.1.0-Linux-x86_64.sh

The issue was not present with
Anaconda3-4.0.0-Linux-x86_64.sh
