### ISSUE TITLE
conda build failure with 1.21.2-py35_0, works when downgraded to 1.20.3-py35_0

### ISSUE THREAD

**Issue by mwiebe** [conda/conda-build#1058]
Here's the error I get:

```
2016-06-27 18:16:05:  0: STDOUT: source tree in: C:\Anaconda3\conda-bld\work
2016-06-27 18:16:05:  0: STDOUT: Traceback (most recent call last):
2016-06-27 18:16:05:  0: STDOUT:   File "C:\Anaconda3\Scripts\conda-build-script.py", line 4, in <module>
2016-06-27 18:16:05:  0: STDOUT:     sys.exit(main())
2016-06-27 18:16:05:  0: STDOUT:   File "C:\Anaconda3\lib\site-packages\conda_build\main_build.py", line 144, in main
2016-06-27 18:16:05:  0: STDOUT:     args_func(args, p)
2016-06-27 18:16:05:  0: STDOUT:   File "C:\Anaconda3\lib\site-packages\conda_build\main_build.py", line 389, in args_func
2016-06-27 18:16:05:  0: STDOUT:     args.func(args, p)
2016-06-27 18:16:05:  0: STDOUT:   File "C:\Anaconda3\lib\site-packages\conda_build\main_build.py", line 332, in execute
2016-06-27 18:16:05:  0: STDOUT:     dirty=args.dirty, activate=args.activate)
2016-06-27 18:16:05:  0: STDOUT:   File "C:\Anaconda3\lib\site-packages\conda_build\build.py", line 563, in build
2016-06-27 18:16:05:  0: STDOUT:     import conda_build.windows as windows
2016-06-27 18:16:05:  0: STDOUT:   File "C:\Anaconda3\lib\site-packages\conda_build\windows.py", line 30, in <module>
2016-06-27 18:16:05:  0: STDOUT:     'installationfolder')
2016-06-27 18:16:05:  0: STDOUT:   File "C:\Anaconda3\lib\distutils\msvc9compiler.py", line 70, in get_value
2016-06-27 18:16:05:  0: STDOUT:     raise KeyError(key)
2016-06-27 18:16:05:  0: STDOUT: KeyError: 'installationfolder'
```

In this build, Python isn't a build dependency and it's overriding any build configuration provided by conda-build anyway.

**Comment by msarahan** [comment]
Sorry about this, this is also reported as #1048.  It has been fixed in #1049 and I'll tag a new release probably tonight.

**Comment by mwiebe** [comment]
No worries, great that there's already a fix!

**Comment by msarahan** [comment]
1.21.3 tagged.  Should be available later today.  Closing this issue for now.

**Comment by ikalev** [comment]
@msarahan  Still getting a similar exception using ``conda-build=1.21.3``:

```
[16:15:51][Step 4/6] Traceback (most recent call last):
[16:15:51][Step 4/6]   File "C:\Anaconda2\Scripts\conda-build-script.py", line 4, in <module>
[16:15:51][Step 4/6]     sys.exit(main())
[16:15:51][Step 4/6]   File "C:\Anaconda2\lib\site-packages\conda_build\main_build.py", line 144, in main
[16:15:51][Step 4/6]     args_func(args, p)
[16:15:51][Step 4/6]   File "C:\Anaconda2\lib\site-packages\conda_build\main_build.py", line 389, in args_func
[16:15:51][Step 4/6]     args.func(args, p)
[16:15:51][Step 4/6]   File "C:\Anaconda2\lib\site-packages\conda_build\main_build.py", line 332, in execute
[16:15:51][Step 4/6]     dirty=args.dirty, activate=args.activate)
[16:15:51][Step 4/6]   File "C:\Anaconda2\lib\site-packages\conda_build\build.py", line 564, in build
[16:15:51][Step 4/6]     windows.build(m, build_file, dirty=dirty, activate=activate)
[16:15:51][Step 4/6]   File "C:\Anaconda2\lib\site-packages\conda_build\windows.py", line 225, in build
[16:15:51][Step 4/6]     fo.write(msvc_env_cmd(bits=cc.bits, override=m.get_value('build/msvc_compiler', None)))
[16:15:51][Step 4/6]   File "C:\Anaconda2\lib\site-packages\conda_build\windows.py", line 130, in msvc_env_cmd
[16:15:51][Step 4/6]     'installationfolder')
[16:15:51][Step 4/6]   File "C:\Anaconda2\lib\distutils\msvc9compiler.py", line 73, in get_value
[16:15:51][Step 4/6]     raise KeyError(key)
[16:15:51][Step 4/6] KeyError: 'installationfolder'
```

However, I do have all relevant versions of VS installed:

```
$ set | findstr VS
VS90COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\Tools\
VS100COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\Tools\
VS140COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
```

**Comment by msarahan** [comment]
Sorry @ikalev this is fixed in #1072, will tag a release soon.

**Comment by ikalev** [comment]
Great, thanks!
