### ISSUE TITLE
%PYTHON% not set when building python

### ISSUE THREAD

**Issue by tomashek** [conda/conda-build#1960]
On Windows, I see failures in Conda-build 2.1.10 when building python itself because the %PYTHON% environment variable is not being set to the python.exe that has just been built. %PYTHON% is just empty. This was not the case in CB1. 

There are simple workarounds, so this is not a show-stopper.

**Comment by msarahan** [comment]
This is the inverse of your issue in https://github.com/conda/conda-build/issues/1898

If we don't set %PERL% when perl is not installed, why would we set %PYTHON% when python isn't installed?

If anyone needs variables set within a build to find an executable that they have produced in their build, they need to handle that.

**Comment by tomashek** [comment]
It is a little different than 1898 because in that instance, perl wasn't being built.

Your own recipes in the AnacondaRecipes repository reference %PYTHON% at the end of the bld.bat script, and since this was fine in CB1, I thought it likely something that should be changed in CB2. This does seem to indicate that you do no use conda-build to build your python.

If you think this is better fixed in the recipe, I will submit a PR to the AnacondaRecipes repo.

**Comment by msarahan** [comment]
That's an excellent point about our recipe being broken.  It is less a case of us not using CB2, and more a case of us using a slightly older version of CB2 that had not fixed #1898, or not building a new python version since updating.

I do think this is better fixed in the recipe.  I think there is sanity in not setting environment variables when tools are not present at build time.  I would replace ```%PYTHON%``` with something like ```%PREFIX%\python```.

**Comment by tomashek** [comment]
Okay, thank you. You can close this issue.
