### ISSUE TITLE
noarch: python path lengths appear to cause breaks on CircleCI

### ISSUE THREAD

**Issue by pmlandwehr** [conda/conda-build#2378]
I've been rebuilding some [conda-forge](https://conda-forge.org/) recipes using the new `noarch: python` flag and have been seeing some build breaks due to path lengths getting too long. e.g. for[`tqdm`](https://github.com/conda-forge/tqdm-feedstock/pull/15) I get:
`FileNotFoundError: [Errno 2] No such file or directory: '/feedstock_root/build_artefacts/tqdm_1505374729453/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/tqdm=tqdm._main:mai'

I've seen the same error when rebuilding [`faker`](https://github.com/conda-forge/faker-feedstock/pull/8), [`pyjwt`](https://github.com/conda-forge/pyjwt-feedstock/pull/6), and [`datadotworld-py`](https://github.com/conda-forge/datadotworld-py-feedstock/pull/1). Has anyone else noticed an uptick in these path issues?

**Comment by mingwandroid** [comment]
I would stay away from `noarch: python` personally. Too many corner cases + bugs.

**Comment by msarahan** [comment]
I would like to support noarch better, but your timing as it stands
coincides with our next Anaconda release.  PRs to fix anything are always
welcome, but I won't be able to look at anything more than a PR for the
next couple of weeks.

**Comment by jjhelmus** [comment]
@pmlandwehr In conda-build 2.x `noarch: python` packages are a bit more picky about the format of the `entry_points` in the `meta.yaml` file.  Specifically, there need to be a space surrounding the equal sign.  So change the tqdm recipe to `- tqdm = tqdm._main:main`.  

This was also reported in #1893 and fixed in #1894 but has not yet been backported to `conda-build` 2.x.  I'll submit a PR shortly for a backport.

**Comment by jjhelmus** [comment]
No PR is needed, the above change was already backported to the 2.1.x branch in #2348. I will be available in the 2.1.18 release.

**Comment by jakirkham** [comment]
My bad. Should have read the issue more closely before redirecting here. Already buried in notifications. 😧

**Comment by jakirkham** [comment]
Circling back to this one.

With `faker` and `datadotworld-py`, it looks like the [previously described issue]( https://github.com/conda/conda-build/issues/2378#issuecomment-329778067 ). So those should be easy to fix.

However with [`pyjwt`]( https://github.com/conda-forge/pyjwt-feedstock/pull/6 ) the entry point should have an acceptable format, but it still fails. Here is the [build log]( https://circleci.com/gh/conda-forge/pyjwt-feedstock/18 ). Not sure why it can't find the entry point, but it misses it.

**Comment by pmlandwehr** [comment]
Thanks everyone for the quick feedback on this!

**Comment by jakirkham** [comment]
After looking at `pyjwt` it looks like the name of the entry point was wrong, which caused it issues. I think this issue can be closed.

**Comment by msarahan** [comment]
Thanks.
