### ISSUE TITLE
Build variants does not work with source repo revision variations

### ISSUE THREAD

**Issue by AntoineD** [conda/conda-build#2450]
With a `meta.yaml` that contains:
```
source:
  svn_url: an_url
  svn_rev: {{ version }}
```
and a `conda_build_config.yaml` with:
```
version:
  - 1
  - 2
```
Both packages are built from the same sources of the first version, the repo is only checked out once.

Am I doing it properly or is it a bug?

**Comment by msarahan** [comment]
This seems like a bug.  What version of conda-build is it?  This seems like something similar I fixed recently.

**Comment by AntoineD** [comment]
I use version 3.0.19, but being stuck on redhat 5 I understood that I shall not go beyond that version.

**Comment by msarahan** [comment]
ah, no, that's not quite accurate, but it is a sticky situation.  It's safe to update conda-build to 3.0.27 (the latest version), but that version is only available as a package on the ``main`` channel, which also includes all of the other redhat 5 incompatible stuff.  I think your best option might be to download the 3.0.27 package you want (the one that matches your python version) from https://repo.continuum.io/pkgs/main/linux-64/ and then manually install it using the path to your downloaded file.  This will not install any dependencies, but since you already have 3.0.19, you should be fine.

```conda install path/to/local/conda-build-3.0.27-(full file name).tar.bz2```

**Comment by AntoineD** [comment]
I updated to conda-build 3.0.27, thx!
Unfortunately the issue remains.

**Comment by AntoineD** [comment]
At the time of the initial issue, I did find a workaround, but after I updated conda-build to 3.8 (still RHEL 5), I'm facing a similar issue where `version` is zipped with other keys:
`ValueError: variant config in config.variant is ambiguous because it does not fully implement all zipped keys, or specifies a subspace that is not fully implemented.`

If I rename the key `version` to something else, then that issue is gone.

Is there something special about using the key `version` with zipped keys?

**Comment by AntoineD** [comment]
It actually has nothing to do with the `version` key, I managed to reproduce the issue with the following recipes:

- `x/meta.yaml`
```
package:
        name: x
        version: {{ bar }}
```
- `x/conda_build_config.yaml`
```
foo:
        - a
        - a
bar:
        - 1
        - 2
zip_keys:
        - bar
        - foo
```
- `xx/meta.yaml`
```
package:
        name: xx
        version: {{ bar }}

requirements:
        build:
                - x
```
- `xx/conda_build_config.yaml`
```
bar:
        - 0
```

The recipe `xx` requires the package `x`, `x` recipe uses `zip_keys` with the same `bar` key as for `xx` but with the `bar` value of `xx` is not in the values of `bar` for `x`.
None of the package shall be already built, then run `conda build xx` and then:
```
Traceback (most recent call last):
  File "/anaconda2/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/anaconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/anaconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 411, in execute
    verify=args.verify)
  File "/anaconda2/lib/python2.7/site-packages/conda_build/api.py", line 199, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/anaconda2/lib/python2.7/site-packages/conda_build/build.py", line 2157, in build_tree
    dep_metas = render_recipe(recipe_dir, config=metadata.config)
  File "/anaconda2/lib/python2.7/site-packages/conda_build/render.py", line 662, in render_recipe
    variants = get_package_variants(m, variants=variants)
  File "/anaconda2/lib/python2.7/site-packages/conda_build/variants.py", line 499, in get_package_variants
    combined_spec, extend_keys = combine_specs(specs, log_output=config.verbose)
  File "/anaconda2/lib/python2.7/site-packages/conda_build/variants.py", line 270, in combine_specs
    log_output=log_output)
  File "/anaconda2/lib/python2.7/site-packages/conda_build/variants.py", line 245, in _combine_spec_dictionaries
    spec_source))
ValueError: variant config in config.variant is ambiguous because it does not fully implement all zipped keys, or specifies a subspace that is not fully implemented.
```

It looks like there is a mismatch of key and context in the `_combine_spec_dictionaries` function.

**Comment by msarahan** [comment]
I think that points to some caching or global variable nonsense.  Thanks for the reproducer code.  I'll work that into a test and try to fix it from there.

**Comment by msarahan** [comment]
Thanks for identifying this.
