### ISSUE TITLE
noarch: python incompatible with certain entry-point script locations

### ISSUE THREAD

**Issue by pmlandwehr** [conda/conda-build#2627]
To be clear at the top, this is an issue I've experienced doing build for conda-forge, and so am unclear if the issue has been resolved in later version of conda-build. 

The issue: adding `noarch: python` to a pure Python module with (some unknown command line script config) and calling `conda-build` yields an error because permission to access the command line script is denied.

I've seen this issue in two feedstocks, though I'm not quite sure *why* it's occurring. What it boils down to is that after adding `noarch: python` and regenerating a repo, the build reports that access to a particular entry point is forbidden. This issue occurs both locally for me and (obvs.) during the CI builds.
* The first example is `docx2txt`, which is pure Python ([Feedstock](https://github.com/conda-forge/docx2txt-feedstock), [repo](https://github.com/ankushshah89/python-docx2txt)). After adding `noarch: python` and regenerating, I get [this error in the CI](https://circleci.com/gh/conda-forge/docx2txt-feedstock/25?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link):
```
+ source /opt/conda/bin/activate /feedstock_root/build_artefacts/docx2txt_1515975702994/_t_env
+ /feedstock_root/build_artefacts/docx2txt_1515975702994/_t_env/bin/python -s /feedstock_root/build_artefacts/docx2txt_1515975702994/test_tmp/run_test.py
import: 'docx2txt'
+ /bin/bash -x -e /feedstock_root/build_artefacts/docx2txt_1515975702994/test_tmp/run_test.sh
+ docx2txt -h
/feedstock_root/build_artefacts/docx2txt_1515975702994/test_tmp/run_test.sh: line 3: /feedstock_root/build_artefacts/docx2txt_1515975702994/_t_env/bin/docx2txt: Permission denied
TESTS FAILED: docx2txt-0.7-py_0.tar.bz2
+ exit 1
Exited with code 1
```

* The second example is `mutagen`, which is 99.9% python and includes one shell script that seems to be unreferenced in the code ([Feedstock](https://github.com/conda-forge/mutagen-feedstock), [repo](https://github.com/quodlibet/mutagen)). After adding `noarch: python` and regenerating, I get [this error in the CI](https://circleci.com/gh/conda-forge/mutagen-feedstock/22?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link):
```
+ source /opt/conda/bin/activate /feedstock_root/build_artefacts/mutagen_1510041584970/_t_env
+ /feedstock_root/build_artefacts/mutagen_1510041584970/_t_env/bin/python -s /feedstock_root/build_artefacts/mutagen_1510041584970/test_tmp/run_test.py
import: 'mutagen'
import: 'mutagen.asf'
import: 'mutagen.id3'
import: 'mutagen.mp4'
+ /bin/bash -x -e /feedstock_root/build_artefacts/mutagen_1510041584970/test_tmp/run_test.sh
+ mid3cp -h
/feedstock_root/build_artefacts/mutagen_1510041584970/test_tmp/run_test.sh: line 3: /feedstock_root/build_artefacts/mutagen_1510041584970/_t_env/bin/mid3cp: Permission denied
TESTS FAILED: mutagen-1.39-py_0.tar.bz2
+ exit 1
Exited with code 1
```

**Comment by jakirkham** [comment]
Basically a consequence of not using Python entry points, but provide custom scripts instead.

**Comment by jakirkham** [comment]
Looking a little more closely, it does appear that `conda-build` correctly places the scripts in the `noarch: python` package in a directory called `python-scripts` as expected. Also `conda` does install these into the correct location as explained in the [`conda` 4.3.0 changelog entry]( https://github.com/conda/conda/blob/10eaf30a42081010a64bf2aa553b97f02a441232/CHANGELOG.md#430-2016-12-14--safety ). However the permissions of these scripts appears to be incorrect. Namely they are not getting executable permissions on Unix. Thus this ultimately is a `conda` problem as the permissions can only be resolved at install time.

**Comment by jjhelmus** [comment]
Both recipes build and test successfully as `noarch: python` packages with conda-build 3.2.2 and conda 4.4.7.

**Comment by mbargull** [comment]
I'd assume someone would have to backport your PR https://github.com/conda/conda-build/pull/2171, @jjhelmus, to `2.1.x` for `conda-forge` if that needs to be fixed before `conda-forge` switches to `conda-build 3.x`.

**Comment by jakirkham** [comment]
Have attempted to backport this to 2.1.x in PR ( https://github.com/conda/conda-build/pull/2653 ).

**Comment by kalefranz** [comment]
`noarch: python` packages should ideally explicitly define entry points in the build section, as in the docs: https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#python-entry-points

```
build:
  entry_points:
    - bsdiff4 = bsdiff4.cli:main_bsdiff4
    - bspatch4 = bsdiff4.cli:main_bspatch4
```

The reason is that, while `noarch: python` works fine on unix after #2653, it's probably still broken on windows.  Conda uses the metadata that gets placed in `info/link.json` to write entry points into the environment, and they differ between unix and windows because windows needs the `-script.py` file along with that `cli-XX.exe` file.  Conda handles all of this, but only if the metadata in `info/link.json` is provided.

As a future improvement, conda-build should probably look at `setup.py` and `entry_points['console_scripts']` for `noarch: python` packages, and then wipe out matches that land in the `python-scripts` directory and ensure those ultimately end up in `info/link.json`.  So that, even if recipe authors forget the `build/entry_points` section in the recipe, it'll ultimately be forgiving.

**Comment by Midnighter** [comment]
I am using [Click](https://click.palletsprojects.com/) to define my CLI. In my `setup.cfg` I have a section that looks like:

```ini
[options.entry_points]
console_scripts =
    mnx-assets = metanetx_assets.cli.cli:cli
```

which works fine when building the package for conda-forge on linux_64 and osx_64. However, on win_64 I get the [following error](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=115273&view=logs&j=240f1fee-52bc-5498-a14a-8361bde76ba0&t=78a0099b-3f13-5ae9-c1f0-24f71d1eac20&l=1686):

```
[noarch_python] Noarch package contains binary script: mnx-assets.exe
```

As mentioned here, specifying the entry point in the `meta.yaml` fixed that problem for me.

```yaml
build:
  noarch: python
  entry_points:
    - "mnx-assets = metanetx_assets.cli.cli:cli"
```

**Comment by flying-sheep** [comment]
Why is it called `entry_points`? Console scripts are only one type of entry points. I filed a bug to clear that up: #4234

**Comment by carlodri** [comment]
Am I stumbling into a similar issue here:

```
Unknown format
   INFO: sysroot: 'C:/Windows/' files: '['winhlp32.exe', 'win.ini', 'twain_32/wiatwain.ds', 'twain_32.dll']'
   INFO (mutmut,Scripts/mutmut.exe): Needed DSO C:/Windows/System32/KERNEL32.dll found in $SYSROOT
   INFO (mutmut,Scripts/mutmut.exe): Needed DSO C:/Windows/System32/SHLWAPI.dll found in $SYSROOT
   INFO (mutmut): Interpreted package 'mutmut' is interpreted by 'python'
[noarch_python] Noarch package contains binary script: mutmut.exe
##[error]Cmd.exe exited with code '1'.

```

source: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=412344&view=logs&j=240f1fee-52bc-5498-a14a-8361bde76ba0&t=06d62fd2-ab49-5add-9ee5-83b6882d7d2b&l=1567

**Comment by mbargull** [comment]
We have docs for `entry_points`
- from Anaconda at
  - https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#python-entry-points
  - https://github.com/conda/conda-build/blob/dc2704352c59e5c6aca9dc8cdfb1c6c2a5906bd5/docs/source/resources/define-metadata.rst#python-entry-points
- and from conda-forge at
  - https://conda-forge.org/docs/maintainer/knowledge_base.html?highlight=entry_points#noarch-python
  - https://github.com/conda-forge/conda-forge.github.io/blob/0a525742bd77a5c1efa4899419c3e3d9f2e8d9ae/src/maintainer/knowledge_base.rst#noarch-python

If you think this needs some clarifications/additions, PRs (for either repo mentioned above) are welcome!
